---
###############################################################################
# Paperless Python Virtual Environment
###############################################################################
# Configure Python Virtual Environment. This is created in the versioned
# install location so state is keep between versions. Assumes archive is
# already unpacked and cleaned.
#
# Args:
#   _paperlessng_venv: str versioned python virtual environment location.
#   _paperlessng_install_dir: str versioned install location.

- name: 'virtualenv | virtual environment configuration (may take a while)'
  ansible.builtin.debug:
    msg: |
      Virtual environment is being configured. This will take a few minutes.

- name: 'virtualenv | setup virtual environment'
  ansible.builtin.pip:
    virtualenv:         '{{ _paperlessng_venv }}'
    virtualenv_command: 'virtualenv'
    virtualenv_python:  'python3'
    requirements:       '{{ _paperlessng_install_dir }}/requirements.txt'
    extra_args:         '--upgrade'
  become: true
  become_user: '{{ paperlessng_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'virtualenv | secure virtual environment'
  ansible.builtin.file:
    path:    '{{ _paperlessng_venv }}'
    owner:   '{{ paperlessng_user }}'
    group:   '{{ paperlessng_group }}'
    mode:    'a-st,g-w,o-rwx'
    state:   'directory'
    recurse: true
